id: P004454
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN7099
  title: རིས་མེད་ཆོས་རིག་གཏེར་མཛོད་ལས། ཐེངས་གཉིས་པ་དང་གསུམ་པ།
  author: ''
  volumes:
    64c2a0c4e15a4d99af54feb172b60906:
      image_group_id: I3CN7101
      title: ''
      volume_number: 1
      total_pages: 236
      base_file: v001.txt
    ed88d8fb4fdc4ab3a1954497ca916e56:
      image_group_id: I3CN7102
      title: ''
      volume_number: 2
      total_pages: 499
      base_file: v002.txt
    110326b703304b56b6694c219f5a0f1f:
      image_group_id: I3CN7103
      title: ''
      volume_number: 3
      total_pages: 294
      base_file: v003.txt
    7a3f9237513548168b6a728fbe52bfb2:
      image_group_id: I3CN7104
      title: ''
      volume_number: 4
      total_pages: 428
      base_file: v004.txt
    b4aff183080b4ab3b93cd81532ba8ee9:
      image_group_id: I3CN7105
      title: ''
      volume_number: 5
      total_pages: 250
      base_file: v005.txt
    d1a8ee5d98e24179841a5b025f9bc0d1:
      image_group_id: I3CN7106
      title: ''
      volume_number: 6
      total_pages: 410
      base_file: v006.txt
    a6ef7f0c482949528f34553bc3efb341:
      image_group_id: I3CN7107
      title: ''
      volume_number: 7
      total_pages: 229
      base_file: v007.txt
    37ee5a4c67904667a250e22b15a6fc55:
      image_group_id: I3CN7108
      title: ''
      volume_number: 8
      total_pages: 330
      base_file: v008.txt
    33739a21512d416183b785316013895c:
      image_group_id: I3CN7109
      title: ''
      volume_number: 9
      total_pages: 180
      base_file: v009.txt
    a43e2ce1f0864f55bc4d258130c641b3:
      image_group_id: I3CN7110
      title: ''
      volume_number: 10
      total_pages: 546
      base_file: v010.txt
    cf18338c39aa4507811676487b54cc59:
      image_group_id: I3CN7111
      title: ''
      volume_number: 11
      total_pages: 438
      base_file: v011.txt
    a5308c855c80468ca4b6ade3ed29fcdd:
      image_group_id: I3CN7112
      title: ''
      volume_number: 12
      total_pages: 374
      base_file: v012.txt
    9294dc19151442478d6004ca68126d48:
      image_group_id: I3CN7113
      title: ''
      volume_number: 13
      total_pages: 436
      base_file: v013.txt
    930ac8c4ad63433994925e5adf3226b1:
      image_group_id: I3CN7114
      title: ''
      volume_number: 14
      total_pages: 401
      base_file: v014.txt
    7d9af870536b409e9405dc25937e288b:
      image_group_id: I3CN7115
      title: ''
      volume_number: 15
      total_pages: 2
      base_file: v015.txt
    f0f002d3be2b458da97d4de2110a2920:
      image_group_id: I3CN7116
      title: ''
      volume_number: 16
      total_pages: 350
      base_file: v016.txt
    f0debecbdffc47389458394f1bf4183b:
      image_group_id: I3CN7117
      title: ''
      volume_number: 17
      total_pages: 287
      base_file: v017.txt
    ac1b8859fa7d4272921d82981eef0b17:
      image_group_id: I3CN7118
      title: ''
      volume_number: 18
      total_pages: 326
      base_file: v018.txt
    54b57ac40e4a440cbece9ead20dfe60b:
      image_group_id: I3CN7119
      title: ''
      volume_number: 19
      total_pages: 2
      base_file: v019.txt
    68b8f696c4de463abc373b16df5b9c46:
      image_group_id: I3CN7120
      title: ''
      volume_number: 20
      total_pages: 520
      base_file: v020.txt
