id: I96BB65BA
legacy_id: P004454
ocr_import_info:
  bdrc_scan_id: W3CN7099
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T13:51:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T12:34:25.291877+00:00'
last_modified: 2022-08-27 20:41:27.014442
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7099
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7099
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིས་མེད་ཆོས་རིག་གཏེར་མཛོད་ལས། ཐེངས་གཉིས་པ་དང་གསུམ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.8800072909917733
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN7119:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7119
      total_pages: 2
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I3CN7119.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9608633175170679
    legacy_id: v019
  I3CN7107:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7107
      total_pages: 229
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN7107.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9665067331151999
    legacy_id: v007
  I3CN7104:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7104
      total_pages: 428
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN7104.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.970136278577539
    legacy_id: v004
  I3CN7114:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7114
      total_pages: 401
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I3CN7114.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7516061200606506
    legacy_id: v014
  I3CN7116:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7116
      total_pages: 350
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I3CN7116.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9723718318905227
    legacy_id: v016
  I3CN7117:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7117
      total_pages: 287
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I3CN7117.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9737150743366824
    legacy_id: v017
  I3CN7105:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7105
      total_pages: 250
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN7105.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9724528174293645
    legacy_id: v005
  I3CN7108:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7108
      total_pages: 330
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN7108.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9747891466529368
    legacy_id: v008
  I3CN7120:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7120
      total_pages: 520
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I3CN7120.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9531653530028523
    legacy_id: v020
  I3CN7103:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7103
      total_pages: 294
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN7103.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9628615693405801
    legacy_id: v003
  I3CN7112:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7112
      total_pages: 374
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3CN7112.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9730246044363685
    legacy_id: v012
  I3CN7109:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7109
      total_pages: 180
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3CN7109.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9713386987475496
    legacy_id: v009
  I3CN7118:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7118
      total_pages: 326
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I3CN7118.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9712281868695463
    legacy_id: v018
  I3CN7106:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7106
      total_pages: 410
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN7106.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9758258916942714
    legacy_id: v006
  I3CN7101:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7101
      total_pages: 236
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7101.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9620859565532469
    legacy_id: v001
  I3CN7111:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7111
      total_pages: 438
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3CN7111.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9714036468124407
    legacy_id: v011
  I3CN7113:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7113
      total_pages: 436
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I3CN7113.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9646290320569428
    legacy_id: v013
  I3CN7110:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7110
      total_pages: 546
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3CN7110.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9779842194675212
    legacy_id: v010
  I3CN7102:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7102
      total_pages: 499
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN7102.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9725400674394141
    legacy_id: v002
  I3CN7115:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7115
      total_pages: 2
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I3CN7115.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9466433640230786
    legacy_id: v015
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
