id: I96BB65BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:56:55+00:00'
last_modified: '2022-06-08T04:40:24.108045+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7099
  title: རིས་མེད་ཆོས་རིག་གཏེར་མཛོད་ལས། ཐེངས་གཉིས་པ་དང་གསུམ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    A97E:
      image_group_id: I3CN7101
      title: ''
      total_pages: 236
      order: 1
      base_file: A97E.txt
    B0CA:
      image_group_id: I3CN7102
      title: ''
      total_pages: 499
      order: 2
      base_file: B0CA.txt
    2E32:
      image_group_id: I3CN7103
      title: ''
      total_pages: 294
      order: 3
      base_file: 2E32.txt
    41DE:
      image_group_id: I3CN7104
      title: ''
      total_pages: 428
      order: 4
      base_file: 41DE.txt
    '1015':
      image_group_id: I3CN7105
      title: ''
      total_pages: 250
      order: 5
      base_file: 1015.txt
    BACB:
      image_group_id: I3CN7106
      title: ''
      total_pages: 410
      order: 6
      base_file: BACB.txt
    103A:
      image_group_id: I3CN7107
      title: ''
      total_pages: 229
      order: 7
      base_file: 103A.txt
    C0A2:
      image_group_id: I3CN7108
      title: ''
      total_pages: 330
      order: 8
      base_file: C0A2.txt
    F741:
      image_group_id: I3CN7109
      title: ''
      total_pages: 180
      order: 9
      base_file: F741.txt
    633E:
      image_group_id: I3CN7110
      title: ''
      total_pages: 546
      order: 10
      base_file: 633E.txt
    F1C4:
      image_group_id: I3CN7111
      title: ''
      total_pages: 438
      order: 11
      base_file: F1C4.txt
    '1920':
      image_group_id: I3CN7112
      title: ''
      total_pages: 374
      order: 12
      base_file: 1920.txt
    E15C:
      image_group_id: I3CN7113
      title: ''
      total_pages: 436
      order: 13
      base_file: E15C.txt
    9A3D:
      image_group_id: I3CN7114
      title: ''
      total_pages: 401
      order: 14
      base_file: 9A3D.txt
    6A72:
      image_group_id: I3CN7115
      title: ''
      total_pages: 2
      order: 15
      base_file: 6A72.txt
    '1877':
      image_group_id: I3CN7116
      title: ''
      total_pages: 350
      order: 16
      base_file: 1877.txt
    767F:
      image_group_id: I3CN7117
      title: ''
      total_pages: 287
      order: 17
      base_file: 767F.txt
    9CCA:
      image_group_id: I3CN7118
      title: ''
      total_pages: 326
      order: 18
      base_file: 9CCA.txt
    '9993':
      image_group_id: I3CN7119
      title: ''
      total_pages: 2
      order: 19
      base_file: 9993.txt
    431C:
      image_group_id: I3CN7120
      title: ''
      total_pages: 520
      order: 20
      base_file: 431C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
